

-- Seed 25 Geography and 25 History questions for the nonstem-games database (80% multiple choice, 20% short answer)
-- Run this after tables are created

INSERT INTO questions (category, difficulty, question_text, correct_answer, question_type, choice_a, choice_b, choice_c, choice_d, image_url)
VALUES
-- Geography (20 multiple choice, 5 short answer)
('Geography', 2, 'What is the capital city of France?', 'Paris', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('Geography', 3, 'Which river is the longest in the world?', 'Nile', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('Geography', 2, 'What is the largest desert in the world?', 'Sahara', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('Geography', 2, 'Which country is known as the Land of the Rising Sun?', 'Japan', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('Geography', 3, 'Which mountain range separates Europe and Asia?', 'Ural Mountains', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('Geography', 3, 'Which continent is the Sahara Desert located in?', 'Africa', 'multiple_choice', 'Asia', 'Africa', 'Australia', 'South America', NULL),
('Geography', 3, 'Which ocean lies on the east coast of the United States?', 'Atlantic Ocean', 'multiple_choice', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', NULL),
('Geography', 4, 'Which country has the most natural lakes?', 'Canada', 'multiple_choice', 'Russia', 'Canada', 'Brazil', 'United States', NULL),
('Geography', 4, 'What is the smallest country in the world?', 'Vatican City', 'multiple_choice', 'Monaco', 'San Marino', 'Vatican City', 'Liechtenstein', NULL),
('Geography', 2, 'Which US state has the most islands?', 'Alaska', 'multiple_choice', 'Florida', 'Alaska', 'Hawaii', 'California', NULL),
('Geography', 3, 'Which city is known as the Big Apple?', 'New York', 'multiple_choice', 'Los Angeles', 'Chicago', 'New York', 'Miami', NULL),
('Geography', 2, 'What is the capital of Australia?', 'Canberra', 'multiple_choice', 'Sydney', 'Melbourne', 'Canberra', 'Perth', NULL),
('Geography', 3, 'Which country is home to the Great Barrier Reef?', 'Australia', 'multiple_choice', 'Australia', 'New Zealand', 'Fiji', 'Papua New Guinea', NULL),
('Geography', 4, 'Which is the largest continent?', 'Asia', 'multiple_choice', 'Africa', 'Europe', 'Asia', 'North America', NULL),
('Geography', 2, 'Which country has the most time zones?', 'France', 'multiple_choice', 'USA', 'Russia', 'France', 'China', NULL),
('Geography', 3, 'Which river flows through Baghdad?', 'Tigris', 'multiple_choice', 'Euphrates', 'Tigris', 'Nile', 'Danube', NULL),
('Geography', 4, 'Which country is both an island and a continent?', 'Australia', 'multiple_choice', 'Greenland', 'Australia', 'Madagascar', 'Iceland', NULL),
('Geography', 2, 'Which city is known as the City of Canals?', 'Venice', 'multiple_choice', 'Amsterdam', 'Venice', 'Bangkok', 'Stockholm', NULL),
('Geography', 3, 'Which is the largest island in the world?', 'Greenland', 'multiple_choice', 'Borneo', 'Greenland', 'New Guinea', 'Sumatra', NULL),
('Geography', 4, 'Which country has the longest coastline?', 'Canada', 'multiple_choice', 'USA', 'Russia', 'Canada', 'Australia', NULL),
('Geography', 2, 'Which is the highest waterfall in the world?', 'Angel Falls', 'multiple_choice', 'Niagara Falls', 'Victoria Falls', 'Angel Falls', 'Iguazu Falls', NULL),
('Geography', 3, 'Which country is known for tulips and windmills?', 'Netherlands', 'multiple_choice', 'Belgium', 'Netherlands', 'Denmark', 'Germany', NULL),
('Geography', 4, 'Which is the largest lake in Africa?', 'Lake Victoria', 'multiple_choice', 'Lake Tanganyika', 'Lake Malawi', 'Lake Victoria', 'Lake Chad', NULL),
('Geography', 2, 'Which city hosted the 2016 Summer Olympics?', 'Rio de Janeiro', 'multiple_choice', 'London', 'Beijing', 'Rio de Janeiro', 'Tokyo', NULL),
('Geography', 3, 'Which country is the world’s largest producer of coffee?', 'Brazil', 'multiple_choice', 'Colombia', 'Vietnam', 'Brazil', 'Ethiopia', NULL),
-- History (20 multiple choice, 5 short answer)
('History', 2, 'Who was the first President of the United States?', 'George Washington', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('History', 3, 'In which year did World War II end?', '1945', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('History', 5, 'What was the name of the ship on which the Pilgrims traveled to America in 1620?', 'Mayflower', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('History', 2, 'Who was known as the Maid of Orléans?', 'Joan of Arc', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('History', 3, 'Who discovered penicillin?', 'Alexander Fleming', 'short_answer', NULL, NULL, NULL, NULL, NULL),
('History', 4, 'Which empire built the Colosseum?', 'Roman Empire', 'multiple_choice', 'Greek Empire', 'Roman Empire', 'Ottoman Empire', 'British Empire', NULL),
('History', 3, 'Who was the British Prime Minister during WWII?', 'Winston Churchill', 'multiple_choice', 'Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Stanley Baldwin', NULL),
('History', 4, 'Which war was fought between the North and South regions in the United States?', 'Civil War', 'multiple_choice', 'Revolutionary War', 'Civil War', 'Vietnam War', 'Korean War', NULL),
('History', 2, 'Who was the first man to step on the moon?', 'Neil Armstrong', 'multiple_choice', 'Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'Michael Collins', NULL),
('History', 3, 'Which country gifted the Statue of Liberty to the USA?', 'France', 'multiple_choice', 'England', 'France', 'Germany', 'Spain', NULL),
('History', 4, 'Who was the longest-reigning British monarch before Queen Elizabeth II?', 'Queen Victoria', 'multiple_choice', 'Queen Victoria', 'King George III', 'Queen Elizabeth I', 'King Henry VIII', NULL),
('History', 2, 'Who was the first emperor of China?', 'Qin Shi Huang', 'multiple_choice', 'Qin Shi Huang', 'Han Wudi', 'Kangxi', 'Yongle', NULL),
('History', 3, 'Which battle marked the end of Napoleon’s rule?', 'Battle of Waterloo', 'multiple_choice', 'Battle of Trafalgar', 'Battle of Leipzig', 'Battle of Waterloo', 'Battle of Austerlitz', NULL),
('History', 4, 'Who was the leader of the Soviet Union during WWII?', 'Joseph Stalin', 'multiple_choice', 'Vladimir Lenin', 'Joseph Stalin', 'Nikita Khrushchev', 'Leonid Brezhnev', NULL),
('History', 2, 'Who was assassinated in Sarajevo in 1914?', 'Archduke Franz Ferdinand', 'multiple_choice', 'Gavrilo Princip', 'Archduke Franz Ferdinand', 'Kaiser Wilhelm II', 'Tsar Nicholas II', NULL),
('History', 3, 'Which document was signed in 1215 limiting the power of the English king?', 'Magna Carta', 'multiple_choice', 'Bill of Rights', 'Petition of Right', 'Magna Carta', 'Habeas Corpus', NULL),
('History', 4, 'Who was the first female Prime Minister of the UK?', 'Margaret Thatcher', 'multiple_choice', 'Theresa May', 'Margaret Thatcher', 'Angela Merkel', 'Indira Gandhi', NULL),
('History', 2, 'Who was the first President of South Africa after apartheid?', 'Nelson Mandela', 'multiple_choice', 'Jacob Zuma', 'Nelson Mandela', 'Thabo Mbeki', 'F.W. de Klerk', NULL),
('History', 3, 'Which civilization built Machu Picchu?', 'Inca', 'multiple_choice', 'Aztec', 'Maya', 'Inca', 'Olmec', NULL),
('History', 4, 'Who was the first Tsar of Russia?', 'Ivan the Terrible', 'multiple_choice', 'Peter the Great', 'Ivan the Terrible', 'Nicholas II', 'Alexander I', NULL),
('History', 2, 'Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'multiple_choice', 'Rosalind Franklin', 'Marie Curie', 'Dorothy Hodgkin', 'Barbara McClintock', NULL),
('History', 3, 'Which country was split into East and West after WWII?', 'Germany', 'multiple_choice', 'Poland', 'Germany', 'Czechoslovakia', 'Austria', NULL),
('History', 4, 'Who was the Egyptian queen famous for her relationships with Julius Caesar and Mark Antony?', 'Cleopatra', 'multiple_choice', 'Nefertiti', 'Cleopatra', 'Hatshepsut', 'Sobekneferu', NULL),
('History', 2, 'Who was the first President of India?', 'Rajendra Prasad', 'multiple_choice', 'Jawaharlal Nehru', 'Rajendra Prasad', 'Indira Gandhi', 'Sarvepalli Radhakrishnan', NULL),
('History', 3, 'Which US President issued the Emancipation Proclamation?', 'Abraham Lincoln', 'multiple_choice', 'Ulysses S. Grant', 'Abraham Lincoln', 'Andrew Johnson', 'James Buchanan', NULL),
('History', 4, 'Who was the first person to circumnavigate the globe?', 'Ferdinand Magellan', 'multiple_choice', 'James Cook', 'Ferdinand Magellan', 'Francis Drake', 'Vasco da Gama', NULL);
-- Country outlines for Geography Game (10 multiple choice)
-- ('Geography', 2, 'Which country is shown in this outline?', 'Australia', 'multiple_choice', 'Australia', 'Canada', 'Kenya', 'Germany', '/assets/country-outlines/australia.svg'),
-- ('Geography', 3, 'Which country is shown in this outline?', 'Canada', 'multiple_choice', 'Canada', 'India', 'Greece', 'Peru', '/assets/country-outlines/canada.svg'),
-- ('Geography', 2, 'Which country is shown in this outline?', 'Germany', 'multiple_choice', 'Germany', 'Senegal', 'Uganda', 'South Korea', '/assets/country-outlines/germany.svg'),
-- ('Geography', 3, 'Which country is shown in this outline?', 'Greece', 'multiple_choice', 'Greece', 'Australia', 'Peru', 'Kenya', '/assets/country-outlines/greece.svg'),
-- ('Geography', 2, 'Which country is shown in this outline?', 'India', 'multiple_choice', 'India', 'Canada', 'Germany', 'Uganda', '/assets/country-outlines/india.svg'),
-- ('Geography', 2, 'Which country is shown in this outline?', 'Kenya', 'multiple_choice', 'Kenya', 'Senegal', 'South Korea', 'Greece', '/assets/country-outlines/kenya.svg'),
-- ('Geography', 3, 'Which country is shown in this outline?', 'Peru', 'multiple_choice', 'Peru', 'Australia', 'India', 'Germany', '/assets/country-outlines/peru.svg'),
-- ('Geography', 3, 'Which country is shown in this outline?', 'Senegal', 'multiple_choice', 'Senegal', 'Kenya', 'Uganda', 'Canada', '/assets/country-outlines/senegal.svg'),
-- ('Geography', 2, 'Which country is shown in this outline?', 'South Korea', 'multiple_choice', 'South Korea', 'Greece', 'Peru', 'Australia', '/assets/country-outlines/south-korea.svg'),
-- ('Geography', 2, 'Which country is shown in this outline?', 'Uganda', 'multiple_choice', 'Uganda', 'India', 'Senegal', 'Germany', '/assets/country-outlines/uganda.svg');